-  name : deploy latest package
   hosts : all
   become : yes
   vars : 
     USERNAME : tomcat_user
   tasks :
     -  name : create user
        ansible.builtin.user :
          name : "{{USERNAME}}"
     -  name : creates directory
        file :
          path : /tom
          state : directory
          owner : "{{USERNAME}}"
          group : "{{USERNAME}}"
          mode : 0755 
     -  name: Extract tomcat
        ansible.builtin.unarchive:
          src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
          dest: /tom
          remote_src: yes
        become_user : "{{USERNAME}}"
     -  name: java install
        ansible.builtin.shell:
          cmd: amazon-linux-extras install java-openjdk11 -y
     -  name: Download war file
        ansible.builtin.get_url:
          url: "{{warurl}}"
          dest: /tom/apache-tomcat-9.0.70/webapps/bs.war
     -  name: tomcat running or not
        ansible.builtin.shell:
          cmd: ps -ef | grep tomcat | grep -v grep
        register: out
        ignore_errors: true
     -  name: tomcat running or not
        ansible.builtin.shell:
          cmd: "nohup sh /tom/apache-tomcat-9.0.70/bin/startup.sh"
        when: out is failed  
     -  name: tomcat running or not
        ansible.builtin.shell:
          cmd: "nohup sh /tom/apache-tomcat-9.0.70/bin/shutdown.sh && nohup sh /tom/apache-tomcat-9.0.70/bin/startup.sh"
        when: out is success
    