-  name : deploy latest package
   hosts : all
   become : yes
   vars : 
     USERNAME : tomcat_user
   tasks :
     -  name : create user
        ansible.builtin.user :
          name : "{{USERNAME}}"
     -  name : creates directory
        file :
          path : /tom
          state : directory
          owner : "{{USERNAME}}"
          group : "{{USERNAME}}"
    -   name: Extract tomcat
        ansible.builtin.unarchive:
          src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
          dest: /tom   
   
  
